version: '3.8'

services:
  app:
    build:
      context: .
    environment:
      NODE_ENV: production
      DATABASE_URL: 'postgresql://postgres:123456@postgres:5432/ssa?schema=public'
    depends_on:
      - postgres
    ports:
      - 3001:3000
    restart: unless-stopped

  postgres:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ssa
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
